# Stub for CoolProp API, needed for autocompletion and convenient class extension
from CoolProp.CoolProp import PyPhaseEnvelopeData, PySpinodalData
from numpy import ndarray
from typing import Any, Iterable


class AbstractState:

    # Accessibles from AbstractState

    def __init__(self, backend: str, fluids: str):
        ...

    def Bvirial(self) -> float:
        ...

    def Cvirial(self) -> float:
        ...

    def PIP(self) -> float:
        ...

    def Prandtl(self) -> float:
        ...

    def Q(self) -> float:
        ...

    def T(self) -> float:
        ...

    def T_critical(self) -> float:
        ...

    def T_reducing(self) -> float:
        ...

    def Tmax(self) -> float:
        ...

    def Tmin(self) -> float:
        ...

    def Ttriple(self) -> float:
        ...

    def acentric_factor(self) -> float:
        ...

    def all_critical_points(self) -> float:
        ...

    def alpha0(self) -> float:
        ...

    def alphar(self) -> float:
        ...

    def apply_simple_mixing_rule(self) -> float:
        ...

    def backend_name(self) -> float:
        ...

    def build_phase_envelope(self) -> float:
        ...

    def build_spinodal(self) -> float:
        ...

    def change_EOS(self, component: int, new_EOS: str) -> float:
        ...

    def chemical_potential(self) -> float:
        ...

    def compressibility_factor(self) -> float:
        ...

    def conductivity(self) -> float:
        ...

    def conductivity_contributions(self) -> float:
        ...

    def conformal_state(self) -> float:
        ...

    def cp0mass(self) -> float:
        ...

    def cp0molar(self) -> float:
        ...

    def cpmass(self) -> float:
        ...

    def cpmolar(self) -> float:
        ...

    def criticality_contour_values(self) -> float:
        ...

    def cvmass(self) -> float:
        ...

    def cvmolar(self) -> float:
        ...

    def d2alpha0_dDelta2(self) -> float:
        ...

    def d2alpha0_dDelta_dTau(self) -> float:
        ...

    def d2alpha0_dTau2(self) -> float:
        ...

    def d2alphar_dDelta2(self) -> float:
        ...

    def d2alphar_dDelta_dTau(self) -> float:
        ...

    def d2alphar_dTau2(self) -> float:
        ...

    def d3alpha0_dDelta2_dTau(self) -> float:
        ...

    def d3alpha0_dDelta3(self) -> float:
        ...

    def d3alpha0_dDelta_dTau2(self) -> float:
        ...

    def d3alpha0_dTau3(self) -> float:
        ...

    def d3alphar_dDelta2_dTau(self) -> float:
        ...

    def d3alphar_dDelta3(self) -> float:
        ...

    def d3alphar_dDelta_dTau2(self) -> float:
        ...

    def d3alphar_dTau3(self) -> float:
        ...

    def d4alphar_dDelta2_dTau2(self) -> float:
        ...

    def d4alphar_dDelta3_dTau(self) -> float:
        ...

    def d4alphar_dDelta4(self) -> float:
        ...

    def d4alphar_dDelta_dTau3(self) -> float:
        ...

    def d4alphar_dTau4(self) -> float:
        ...

    def dalpha0_dDelta(self) -> float:
        ...

    def dalpha0_dTau(self) -> float:
        ...

    def dalphar_dDelta(self) -> float:
        ...

    def dalphar_dTau(self) -> float:
        ...

    def delta(self) -> float:
        ...

    def first_partial_deriv(self) -> float:
        ...

    def first_saturation_deriv(self) -> float:
        ...

    def first_two_phase_deriv(self) -> float:
        ...

    def first_two_phase_deriv_splined(self) -> float:
        ...

    def fluid_names(self) -> float:
        ...

    def fluid_param_string(self) -> float:
        ...

    def fugacity(self) -> float:
        ...

    def fugacity_coefficient(self) -> float:
        ...

    def fundamental_derivative_of_gas_dynamics(self) -> float:
        ...

    def gas_constant(self) -> float:
        ...

    def get_binary_interaction_double(self, component1: str | int, component2: str | int) -> float:
        ...

    def get_binary_interaction_string(self, component1: str | int, component2: str | int) -> str:
        ...

    def get_fluid_constant(self, component_index: int, const_key: int) -> float:
        ...

    def get_fluid_parameter_double(self, component: int, param: str) -> float:
        ...

    def get_mass_fractions(self) -> list[float]:
        ...

    def get_mole_fractions(self) -> list[float]:
        ...

    def get_phase_envelope_data(self) -> PyPhaseEnvelopeData:
        ...

    def get_spinodal_data(self) -> PySpinodalData:
        ...

    def gibbsmass(self) -> float:
        ...

    def gibbsmass_excess(self) -> float:
        ...

    def gibbsmolar(self) -> float:
        ...

    def gibbsmolar_excess(self) -> float:
        ...

    def gibbsmolar_residual(self) -> float:
        ...

    def has_melting_line(self) -> bool:
        ...

    def helmholtzmass(self) -> float:
        ...

    def helmholtzmass_excess(self) -> float:
        ...

    def helmholtzmolar(self) -> float:
        ...

    def helmholtzmolar_excess(self) -> float:
        ...

    def hmass(self) -> float:
        ...

    def hmass_excess(self) -> float:
        ...

    def hmass_idealgas(self) -> float:
        ...

    def hmolar(self) -> float:
        ...

    def hmolar_excess(self) -> float:
        ...

    def hmolar_idealgas(self) -> float:
        ...

    def hmolar_residual(self) -> float:
        ...

    def ideal_curve(self) -> float:
        ...

    def isobaric_expansion_coefficient(self) -> float:
        ...

    def isothermal_compressibility(self) -> float:
        ...

    def keyed_output(self, param_key: int) -> float | str:
        ...

    def melting_line(self) -> float:
        ...

    def molar_mass(self) -> float:
        ...

    def mole_fractions_liquid(self) -> float:
        ...

    def mole_fractions_vapor(self) -> float:
        ...

    def name(self) -> float:
        ...

    def neff(self) -> float:
        ...

    def p(self) -> float:
        ...

    def p_critical(self) -> float:
        ...

    def phase(self) -> int:
        ...

    def pmax(self) -> float:
        ...

    def rhomass(self) -> float:
        ...

    def rhomass_critical(self) -> float:
        ...

    def rhomass_reducing(self) -> float:
        ...

    def rhomolar(self) -> float:
        ...

    def rhomolar_critical(self) -> float:
        ...

    def rhomolar_reducing(self) -> float:
        ...

    def saturated_liquid_keyed_output(self, param_key: int) -> float:
        ...

    def saturated_vapor_keyed_output(self, param_key: int) -> float:
        ...

    def saturation_ancillary(self) -> float:
        ...

    def second_partial_deriv(self) -> float:
        ...

    def second_saturation_deriv(self) -> float:
        ...

    def second_two_phase_deriv(self) -> float:
        ...

    def set_binary_interaction_double(self) -> float:
        ...

    def set_binary_interaction_string(self) -> float:
        ...

    def set_cubic_alpha_C(self) -> float:
        ...

    def set_fluid_parameter_double(self) -> float:
        ...

    def set_mass_fractions(self, mass_fractions: Iterable[float]):
        ...

    def set_mole_fractions(self, mole_fractions: Iterable[float]) -> float:
        ...

    def set_volu_fractions(self, volu_fractions: Iterable[float]) -> float:
        ...

    def smass(self) -> float:
        ...

    def smass_excess(self) -> float:
        ...

    def smass_idealgas(self) -> float:
        ...

    def smolar(self) -> float:
        ...

    def smolar_excess(self) -> float:
        ...

    def smolar_idealgas(self) -> float:
        ...

    def smolar_residual(self) -> float:
        ...

    def specify_phase(self, imposed_phase_key: int) -> float:
        ...

    def speed_sound(self) -> float:
        ...

    def surface_tension(self) -> float:
        ...

    def tangent_plane_distance(self) -> float:
        ...

    def tau(self) -> float:
        ...

    def trivial_keyed_output(self, params_key: int) -> float:
        ...

    def true_critical_point(self) -> float:
        ...

    def umass(self) -> float:
        ...

    def umass_excess(self) -> float:
        ...

    def umass_idealgas(self) -> float:
        ...

    def umolar(self) -> float:
        ...

    def umolar_excess(self) -> float:
        ...

    def umolar_idealgas(self) -> float:
        ...

    def unspecify_phase(self):
        ...

    def update(self, input_pair_key: int, input1: float, input2: float):
        ...

    def update_QT_pure_superanc(self, Q: float, T: float) -> float:
        ...

    def update_with_guesses(
            self, input_pair_key: int, input1: float, input2: float, guesse: Any) -> float:
        ...

    def viscosity(self) -> float:
        ...

    def viscosity_contributions(self) -> float:
        ...

    def volumemass_excess(self) -> float:
        ...

    def volumemolar_excess(self) -> float:
        ...
