from __future__ import annotations
from typing import Any


class AbstractState:

    def __init__(self, backend: str, fluid: str) -> None:
        ...

    def Bvirial(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def Cvirial(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def PIP(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def Prandtl(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def Q(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def T(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def T_critical(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def T_reducing(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def Tmax(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def Tmin(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def Ttriple(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def acentric_factor(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def all_critical_points(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def alpha0(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def alphar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def apply_simple_mixing_rule(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def backend_name(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def build_phase_envelope(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def build_spinodal(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def change_EOS(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def chemical_potential(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def compressibility_factor(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def conductivity(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def conductivity_contributions(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def conformal_state(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def cp0mass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def cp0molar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def cpmass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def cpmolar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def criticality_contour_values(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def cvmass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def cvmolar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d2alpha0_dDelta2(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d2alpha0_dDelta_dTau(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d2alpha0_dTau2(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d2alphar_dDelta2(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d2alphar_dDelta_dTau(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d2alphar_dTau2(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d3alpha0_dDelta2_dTau(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d3alpha0_dDelta3(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d3alpha0_dDelta_dTau2(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d3alpha0_dTau3(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d3alphar_dDelta2_dTau(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d3alphar_dDelta3(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d3alphar_dDelta_dTau2(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d3alphar_dTau3(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d4alphar_dDelta2_dTau2(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d4alphar_dDelta3_dTau(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d4alphar_dDelta4(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d4alphar_dDelta_dTau3(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def d4alphar_dTau4(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def dalpha0_dDelta(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def dalpha0_dTau(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def dalphar_dDelta(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def dalphar_dTau(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def delta(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def first_partial_deriv(self, of_key: int, wrt_key: int, const_key: int) -> float:
        ...

    def first_saturation_deriv(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def first_two_phase_deriv(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def first_two_phase_deriv_splined(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def fluid_names(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def fluid_param_string(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def fugacity(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def fugacity_coefficient(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def fundamental_derivative_of_gas_dynamics(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def gas_constant(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def get_binary_interaction_double(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def get_binary_interaction_string(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def get_fluid_constant(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def get_fluid_parameter_double(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def get_mass_fractions(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def get_mole_fractions(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def get_phase_envelope_data(self, *args: Any, **kwargs: Any) -> PyPhaseEnvelopeData:
        ...

    def get_spinodal_data(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def gibbsmass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def gibbsmass_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def gibbsmolar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def gibbsmolar_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def gibbsmolar_residual(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def has_melting_line(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def helmholtzmass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def helmholtzmass_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def helmholtzmolar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def helmholtzmolar_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def hmass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def hmass_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def hmass_idealgas(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def hmolar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def hmolar_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def hmolar_idealgas(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def hmolar_residual(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def ideal_curve(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def isobaric_expansion_coefficient(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def isothermal_compressibility(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def keyed_output(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def melting_line(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def molar_mass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def mole_fractions_liquid(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def mole_fractions_vapor(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def name(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def neff(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def p(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def p_critical(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def phase(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def pmax(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def rhomass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def rhomass_critical(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def rhomass_reducing(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def rhomolar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def rhomolar_critical(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def rhomolar_reducing(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def saturated_liquid_keyed_output(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def saturated_vapor_keyed_output(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def saturation_ancillary(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def second_partial_deriv(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def second_saturation_deriv(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def second_two_phase_deriv(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def set_binary_interaction_double(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def set_binary_interaction_string(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def set_cubic_alpha_C(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def set_fluid_parameter_double(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def set_mass_fractions(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def set_mole_fractions(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def set_volu_fractions(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def smass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def smass_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def smass_idealgas(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def smolar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def smolar_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def smolar_idealgas(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def smolar_residual(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def specify_phase(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def speed_sound(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def surface_tension(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def tangent_plane_distance(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def tau(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def trivial_keyed_output(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def true_critical_point(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def umass(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def umass_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def umass_idealgas(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def umolar(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def umolar_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def umolar_idealgas(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def unspecify_phase(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def update(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def update_QT_pure_superanc(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def update_with_guesses(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def viscosity(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def viscosity_contributions(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def volumemass_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...

    def volumemolar_excess(self, *args: Any, **kwargs: Any) -> Any:
        ...


class PyPhaseEnvelopeData:
    K: list[float]
    Q: list[float]
    T: list[float]
    TypeI: list[float]
    hmolar_liq: list[float]
    hmolar_vap: list[float]
    iTsat_max: list[float]
    icrit: list[float]
    ipsat_max: list[float]
    lnT: list[float]
    lnp: list[float]
    lnrhomolar_liq: list[float]
    lnrhomolar_vap: list[float]
    p: list[float]
    rhomolar_liq: list[float]
    rhomolar_vap: list[float]
    smolar_liq: list[float]
    smolar_vap: list[float]
    x: list[float]
    y: list[float]
